export type PartCategoryType =
	| "SCREEN"
	| "BATTERY"
	| "CHARGING_PORT"
	| "CAMERA"
	| "SPEAKER"
	| "MICROPHONE"
	| "MOTHERBOARD"
	| "HOUSING"
	| "BUTTON"
	| "OTHER";

export const PartCategory: Record<string, PartCategoryType> = {
	SCREEN: "SCREEN",
	BATTERY: "BATTERY",
	CHARGING_PORT: "CHARGING_PORT",
	CAMERA: "CAMERA",
	SPEAKER: "SPEAKER",
	MICROPHONE: "MICROPHONE",
	MOTHERBOARD: "MOTHERBOARD",
	HOUSING: "HOUSING",
	BUTTON: "BUTTON",
	OTHER: "OTHER",
};
